language: cpp
compiler:
- gcc

#install:
#- cmake --version

script:
- mkdir build
- cd build
- cmake ..
#- cmake --build .
- make
- ctest -VV

#after_success:
#- make test
#- coveralls --exclude "test" --exclude "CMakeFiles" --include "lib/" 
