language: cpp
compiler: gcc
os: linux
dist: bionic

include:
  - os: linux
    addons:
      apt:
        packages:
          - clang-format-8

before_install:
  - find src/ include/ test/ -type f \( -iname \*.h -o -iname \*.cpp \) | xargs -I _ clang-format -style=file -output-replacements-xml _ | grep -c "<replacement " >/dev/null
  - if [ $? -ne 1 ]; then echo "Not all source and header files are formatted with clang-format"; exit 1; fi

script:
  - bash install.sh

notifications:
  email: false

