language: cpp
compiler:
- gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
- bash install.sh

#after_success:
#- make test
#- coveralls --exclude "test" --exclude "CMakeFiles" --include "lib/" 

notifications:
  email: false
