# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
script:
- bash install.sh

#after_success:
#- make test
#- coveralls --exclude "test" --exclude "CMakeFiles" --include "lib/" 

notifications:
  email: false
