language: cpp
compiler:
- gcc

#install:
#- cmake --version

script:
- bash install.sh

#after_success:
#- make test
#- coveralls --exclude "test" --exclude "CMakeFiles" --include "lib/" 

#notifications:
#  email: false
