language: cpp

matrix:
  include:
    - os: linux
      compiler: g++
    - os: osx
      compiler: clang

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq

install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq g++-4.8; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-4.8"; fi

script:
  - bash install.sh

notifications:
  email: false
