output_folder: "output_toy_example_workflow"
original_prg: "prgs/toy_prg.fa"

coverages:
  - 100

subsamplings:
  - random

technologies:
  - illumina

samples: config/samples_small.csv
subsampled_reads_dir: config/subsampled_reads_small.csv

msas_dir: msas
msas_csv: config/msas_small.csv

# time and memory limits
make_prg_timeout_in_second: 86400 # 1 days
make_prg_memory_limit: 32000 # memory limit
clustalo_timeout_in_second: 86400 # 1 days

pandora_container: docker://leandroishilima/pandora_analysis_pipeline:pandora_paper_tag1
